qldf/root/views.py
import json
from functools import wraps
from time import time

from flask import Blueprint, render_template, session, url_for, g, request, current_app, redirect
from sqlalchemy import func, desc, asc, literal

from qldf import db
from qldf.models import Player, Record, Map, WorkshopItem, Server
from .forms import SearchForm

root = Blueprint('root', __name__, url_prefix='/', template_folder='templates', static_folder='static', static_url_path='root/static')


def search_form(wrapped_function, *args, **kwargs):
    """To be used on every routing function that extends base.j2 to handle the search form in the page header.
    Requires methods GET and POST enabled"""
    @wraps(wrapped_function)
    def wrapper(*args, **kwargs):
        g.search_form = SearchForm()
        if g.search_form.validate_on_submit() and g.search_form.search.data:
            # redirect to search results if search was made
            return redirect(url_for('root.search', search_string=g.search_form.search_string.data))
        else:
            return wrapped_function(*args, **kwargs)
    return wrapper


@root.route('/', methods=['GET', 'POST'])
@search_form
def index():
    # Get rows of recent records
    recent_records = db.session.query(Record.mode,
                                      Map.name.label('map_name'),
                                      Player.name.label('player_name'),
                                      Player.steam_id,
                                      Record.time,
                                      Record.date,
                                      func.rank().over(
                                          order_by=Record.time,
                                          partition_by=(Record.map_id, Record.mode)
                                      ).label('rank')).\
        join(Player, Map).\
        order_by(desc(Record.date)).\
        limit(current_app.config['NUM_RECENT_RECORDS'])

    # Get rows of recent world records
    sq = db.session.query(Record.id,
                          func.rank().over(
                              order_by=Record.time,
                              partition_by=(Record.map_id, Record.mode)
                          ).label('rank')).subquery()
    recent_world_records = db.session.query(Record.mode,
                                            Map.name.label('map_name'),
                                            Player.name.label('player_name'),
                                            Player.steam_id,
                                            Record.time,
                                            Record.date,
                                            sq.c.rank.label('rank')).\
        join(Player, Map).\
        join(sq, sq.c.id == Record.id).\
        filter(sq.c.rank == 1).\
        order_by(desc(Record.date)).\
        limit(current_app.config['NUM_RECENT_WORLD_RECORDS'])
    # Get rows of recent maps
    recent_maps = db.session.query(Map.name,
                                   Map.date_created).\
        order_by(desc(Map.date_created)).\
        limit(current_app.config['NUM_RECENT_MAPS'])
    return render_template('index.j2',
                           recent_records=recent_records,
                           recent_world_records=recent_world_records,
                           recent_maps=recent_maps)


@root.route('servers/', methods=['GET', 'POST'])
@search_form
def servers():
    """Show server list"""
    _servers = db.session.query(Server).all()
    # Parse players json
    players = {}
    for server in _servers:
        db_players = json.loads(server.players)
        players[server.server_id] = []
        for _player in db_players:
            players[server.server_id].append({'name': _player['name'],
                                              'score': _player['score'],
                                              'totalConnected': _player['totalConnected']})
            # Sort players by fastest time
            players[server.server_id] = sorted(players[server.server_id], key=lambda k: k['score'])
    # Sort servers by playercount
    _servers = sorted(_servers, key=lambda k: len(players[k.server_id]), reverse=True)
    # Subquery to get all record ranks per map
    map_names = list(set([x.map for x in _servers]))
    sq = db.session.query(Map.name.label('map_name'),
                          Record.mode,
                          Record.date,
                          Record.time,
                          Player.name.label('player_name'),
                          Player.steam_id,
                          func.rank().over(
                              order_by=Record.time,
                              partition_by=(Record.map_id, Record.mode)
                          ).label('rank')).\
        join(Record, Player).\
        filter(Map.name.in_(map_names)).\
        subquery()
    # Keep only the #1 ranks
    world_records_unlinked = db.session.query(sq.c.map_name.label('map_name'),
                                     sq.c.mode.label('mode'),
                                     sq.c.date.label('date'),
                                     sq.c.time.label('time'),
                                     sq.c.player_name.label('player_name'),
                                     sq.c.steam_id.label('steam_id'),
                                     sq.c.rank.label('rank')).\
        filter(sq.c.rank==1).all()
    # Link world records to server_id by unique map names
    world_records = {}
    for _server in _servers:
        world_records[_server.server_id] = []
        for wr in world_records_unlinked:
            if wr.map_name == _server.map:
                world_records[_server.server_id].append(wr)

    return render_template('servers.j2',
                           servers=_servers,
                           players=players,
                           world_records=world_records)


@root.route('player/<string:steam_id>/', defaults={'page': 1, 'sortby': 'date', 'sortdir': 'desc'}, methods=['GET', 'POST'])
@root.route('player/<string:steam_id>/<int:page>/<string:sortby>/<string:sortdir>/', methods=['GET', 'POST'])
@root.route('player/<string:steam_id>/<int:page>/<string:sortby>/', defaults={'sortdir': 'asc'}, methods=['GET', 'POST'])
@root.route('player/<string:steam_id>/<int:page>/', defaults={'sortby': 'date', 'sortdir': 'desc'}, methods=['GET', 'POST'])
@search_form
def player(page, steam_id, sortby, sortdir):
    """Show records and stats for a single player"""
    if sortdir == 'asc':
        sortdir = asc
    else:
        sortdir = desc
    # Get 'rank' in subquery before filtering on player name and ordering
    sq = db.session.query(Record.mode.label('mode'),
                          Record.time.label('time'),
                          Record.date.label('date'),
                          Record.player_id.label('player_id'),
                          Map.name.label('map_name'),
                          func.rank().over(
                              order_by=Record.time,
                              partition_by=(Record.map_id, Record.mode)
                          ).label('rank')).\
        join(Map).\
        subquery()
    pagination = db.session.query(Player.id,
                                  Player.steam_id,
                                  Player.name.label('player_name'),
                                  Player.date_modified,
                                  Player.avatar_url,
                                  sq.c.mode.label('mode'),
                                  sq.c.time.label('time'),
                                  sq.c.date.label('date'),
                                  sq.c.map_name.label('map_name'),
                                  sq.c.rank.label('rank')).\
        join(sq, sq.c.player_id == Player.id).\
        filter(Player.steam_id == steam_id).\
        order_by(sortdir(sortby)).\
        paginate(page, current_app.config['ROWS_PER_PAGE'], True)
    name = pagination.items[0].player_name
    avatar_url = pagination.items[0].avatar_url
    date_modified = pagination.items[0].date_modified
    return render_template('player.j2',
                           title=steam_id,
                           name=name,
                           steam_id=steam_id,
                           avatar_url=avatar_url,
                           date_modified=date_modified,
                           pagination=pagination,
                           sortdir=sortdir.__name__,
                           reverse_sortdir_on=sortby)


@root.route('players/', defaults={'page': 1, 'sortby': 'name', 'sortdir': 'asc'}, methods=['GET', 'POST'])
@root.route('players/<int:page>/', defaults={'sortby': 'name', 'sortdir': 'asc'}, methods=['GET', 'POST'])
@root.route('players/<int:page>/<string:sortby>/<string:sortdir>/', methods=['GET', 'POST'])
@root.route('players/<int:page>/<string:sortby>/', defaults={'sortdir': 'asc'}, methods=['GET', 'POST'])
@search_form
def players(page, sortby, sortdir):
    """Show a list of all players and their number of records and world records."""
    if sortdir == 'asc':
        sortdir = asc
    else:
        sortdir = desc
    # subquery to get all record ranks per player
    sq = db.session.query(Player.id.label('id'),
                          func.rank().over(
                              order_by=Record.time,
                              partition_by=(Record.map_id, Record.mode)
                          ).label('rank')).\
        join(Player.records).\
        subquery()
    # subquery to get wr count per player
    sq2 = db.session.query(Player.id.label('id'),
                           func.count(sq.c.id).label('wr_count')).\
        join(sq, sq.c.id == Player.id).\
        filter(sq.c.rank == 1).\
        group_by(Player.id).\
        subquery()
    # subquery to get record count per player
    sq3 = db.session.query(Player.id.label('id'),
                           func.count(Player.id).label('record_count')).\
        join(Player.records).\

qldf/root/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('root.static', filename='icon.ico') }}">
    <meta charset="UTF-8">
    {% if title %}
    <title>{{ title }} - www.qldf.com</title>
    {% else %}
    <title>www.qldf.com</title>
    {% endif %}
    <script>
        function startTime() {
            var today = new Date();
            var h = today.getHours();
            var m = today.getMinutes();
            var s = today.getSeconds();
            m = checkTime(m);
            s = checkTime(s);
            document.getElementById('digital_clock').innerHTML =
            h + ":" + m + ":" + s;
            var t = setTimeout(startTime, 500);
        }
        function checkTime(i) {
            if (i < 10) {i = "0" + i};
            return i;
        }
    </script>
</head>
<body onload="startTime()">
    <ul>
        {% for item in nav.main %}
            <li>
                <a href="{{ item.url }}">{{ item.label }}</a>
            </li>
        {% endfor %}
    </ul>
    {% from "macros.html" import render_form %}
    {% if g.search_form %}
    {{ render_form(g.search_form) }}
    {% endif %}
    <br><hr>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                <li><div>{{ message }}<</div></li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    <div>{% block content %}{% endblock %}</div>
    <div><hr>© Daan Lubbers 2017. <a href="https://www.github.com/daan4/qldf">GitHub Repository</a>. Rendered by <a href="http://flask.pocoo.org/">Flask</a> in __EXECUTION_TIME__.<br/>
        Inspired by <a href="https://qlrace.com">qlrace.com</a>, <a href="https://q3df.org">q3df.org</a> and <a href="https://reflexrace.github.io">reflexrace.github.io</a> . </div>
</body>
</html>

qldf/root/templates/macros.html
{% macro render_field(field) %}
    {% if field.name != 'csrf_token' %}
        <dt>{{ field.label }}
        <dd>{{ field(**kwargs) }}
        {% if field.errors %}
        <ul>
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </dd>
    {% endif %}
{% endmacro %}

{% macro render_form(form) %}
    <form action="" method="post" name="{{ form.name }}">
        {{ form.hidden_tag() }}
        {% for field in form %}
            {{ render_field(field) }}
        {% endfor %}
    </form>
{% endmacro %}

qldf/root/templates/macros.j2
{% macro render_field(field) %}
    {% if field.name != 'csrf_token' %}
        <dt>{{ field.label }}
        <dd>{{ field(**kwargs) }}
        {% if field.errors %}
        <ul>
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </dd>
    {% endif %}
{% endmacro %}

{% macro render_form(form) %}
    <form action="" method="post" name="{{ form.name }}">
        {{ form.hidden_tag() }}
        {% for field in form %}
            {{ render_field(field) }}
        {% endfor %}
    </form>
{% endmacro %}

qldf/root/templates/map.html
{% extends "base.html" %}
{% block content %}
Map data<br/>
Name: {{ map_data.map_name }}<br/>
{% if map_data.item_id %}
Workshop item link: {{ map_data.item_id | format_workshop_url }}<br/>
Workshop item name: {{ name }}<br/>
Workshop item author: {{ map_data.author_steam_id | format_profile_url }}<br/>
Workshop item description: {{ map_data.description | print_newlines }}<br/>
Workshop item upload date: {{ map_data.date | format_record_date }}<br/>
Workshop item filesize: {{ map_data.size }} MB<br/>
Workshop item comment count: {{ map_data.num_comments }}<br/>
Workshop item rating: {{ map_data.score }}<br/>
Workshop item rating count: {{ map_data.num_scores }}<br/>
Workshop item preview image: <img src="{{ map_data.preview_url }}"/><br/>
{% endif %}
Records
<table>
    <tr>
        <th>{{ 'Rank' | format_sortable_table_header('rank', sortdir, reverse_sortdir_on, name=name, page=pagination.page) }}</th>
        <th>{{ 'Player' | format_sortable_table_header('player_name', sortdir, reverse_sortdir_on, name=name, page=pagination.page) }}</th>
        <th>{{ 'Mode' | format_sortable_table_header('mode', sortdir, reverse_sortdir_on, name=name, page=pagination.page) }}</th>
        <th>{{ 'Time' | format_sortable_table_header('time', sortdir, reverse_sortdir_on, name=name, page=pagination.page) }}</th>
        <th>{{ 'Date' | format_sortable_table_header('date', sortdir, reverse_sortdir_on, name=name, page=pagination.page) }}</th>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.rank }}</td>
        <td>{{ row.player_name | format_player_name(row.steam_id) }}</td>
        <td>{{ row.mode | format_record_mode }}</td>
        <td>{{ row.time | format_record_time }}</td>
        <td>{{ row.date | format_record_date }}</td>
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root._map', page=pagination.prev_num, name=name) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root._map', page=pagination.next_num, name=name) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/maps.html
{% extends "base.html" %}
{% block content %}
    Maps
<table>
    <tr>
        <th>{{ 'Name' | format_sortable_table_header('map_name', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Records' | format_sortable_table_header('record_count', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>Steam Workshop URL</th>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.map_name | format_map_name }}</td>
        <td>{{ row.record_count }}</td>
        <td>{{ row.item_id | format_workshop_url }}</td>
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root.maps', page=pagination.prev_num) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root.maps', page=pagination.next_num) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/maps.j2
{% extends "base.j2" %}
{% block content %}
    Maps
<table>
    <tr>
        <th>{{ 'Name' | format_sortable_table_header('map_name', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Records' | format_sortable_table_header('record_count', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>Steam Workshop URL</th>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.map_name | format_map_name }}</td>
        <td>{{ row.record_count }}</td>
        <td>{{ row.item_id | format_workshop_url }}</td>
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root.maps', page=pagination.prev_num) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root.maps', page=pagination.next_num) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/player.html
{% extends "base.html" %}
{% block content %}
{{ name }}<br/>
Steam Profile: {{ steam_id | format_profile_url }}<br/>
Records
<table>
    <tr>
        <th>{{ 'Map' | format_sortable_table_header('map_name', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
        <th>{{ 'Mode' | format_sortable_table_header('mode', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
        <th>{{ 'Rank' | format_sortable_table_header('rank', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
        <th>{{ 'Time' | format_sortable_table_header('time', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
        <th>{{ 'Date' | format_sortable_table_header('date', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.map_name | format_map_name }}</td>
        <td>{{ row.mode | format_record_mode }}</td>
        <td>{{ row.rank }}</td>
        <td>{{ row.time | format_record_time }}</td>
        <td>{{ row.date | format_record_date }}</td>
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root.player', page=pagination.prev_num, name=name, steam_id=steam_id) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root.player', page=pagination.next_num, name=name, steam_id=steam_id) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/player.j2
{% extends "base.j2" %}
{% block content %}
{{ name }}<br/>
Steam Profile: {{ steam_id | format_profile_url }}<br/>
Steam Avatar: <img src="{{ avatar_url }}"/><br/>
Name and avatar last updated on: {{ date_modified | format_record_date }} <br/>
Records
<table>
    <tr>
        <th>{{ 'Map' | format_sortable_table_header('map_name', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
        <th>{{ 'Mode' | format_sortable_table_header('mode', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
        <th>{{ 'Rank' | format_sortable_table_header('rank', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
        <th>{{ 'Time' | format_sortable_table_header('time', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
        <th>{{ 'Date' | format_sortable_table_header('date', sortdir, reverse_sortdir_on, name=name, page=pagination.page, steam_id=steam_id) }}</th>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.map_name | format_map_name }}</td>
        <td>{{ row.mode | format_record_mode }}</td>
        <td>{{ row.rank }}</td>
        <td>{{ row.time | format_record_time }}</td>
        <td>{{ row.date | format_record_date }}</td>
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root.player', page=pagination.prev_num, name=name, steam_id=steam_id) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root.player', page=pagination.next_num, name=name, steam_id=steam_id) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/players.html
{% extends "base.html" %}
{% block content %}
Players
<table>
    <tr>
        <th>{{ 'Name' | format_sortable_table_header('name', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'World Records' | format_sortable_table_header('wr_count', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Records' | format_sortable_table_header('record_count', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <td>Steam Profile</td>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.name | format_player_name(row.steam_id) }}</td>
        <td>{{ row.wr_count }}</td>
        <td>{{ row.record_count }}</td>
        <td>{{ row.steam_id | format_profile_url }}</td>
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root.players', page=pagination.prev_num) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root.players', page=pagination.next_num) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/players.j2
{% extends "base.j2" %}
{% block content %}
Players
<table>
    <tr>
        <th>{{ 'Name' | format_sortable_table_header('name', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'World Records' | format_sortable_table_header('wr_count', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Records' | format_sortable_table_header('record_count', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <td>Steam Profile</td>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.name | format_player_name(row.steam_id) }}</td>
        <td>{{ row.wr_count }}</td>
        <td>{{ row.record_count }}</td>
        <td>{{ row.steam_id | format_profile_url }}</td>
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root.players', page=pagination.prev_num) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root.players', page=pagination.next_num) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/records.html
{% extends "base.html" %}
{% block content %}
    Records
<table>
    <tr>
        <th>{{ 'Map' | format_sortable_table_header('map_name', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Mode' | format_sortable_table_header('mode', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Player' | format_sortable_table_header('player_name', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Rank' | format_sortable_table_header('rank', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Time' | format_sortable_table_header('time', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Date' | format_sortable_table_header('date', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.map_name | format_map_name }}</td>
        <td>{{ row.mode | format_record_mode }}</td>
        <td>{{ row.player_name | format_player_name(row.steam_id) }}</td>
        <td>{{ row.rank }}</td>
        <td>{{ row.time | format_record_time }}</td>
        <td>{{ row.date | format_record_date }}</td>
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root.records', page=pagination.prev_num) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root.records', page=pagination.next_num) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/records.j2
{% extends "base.j2" %}
{% block content %}
    Records
<table>
    <tr>
        <th>{{ 'Map' | format_sortable_table_header('map_name', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Mode' | format_sortable_table_header('mode', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Player' | format_sortable_table_header('player_name', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Rank' | format_sortable_table_header('rank', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Time' | format_sortable_table_header('time', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
        <th>{{ 'Date' | format_sortable_table_header('date', sortdir, reverse_sortdir_on, page=pagination.page) }}</th>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.map_name | format_map_name }}</td>
        <td>{{ row.mode | format_record_mode }}</td>
        <td>{{ row.player_name | format_player_name(row.steam_id) }}</td>
        <td>{{ row.rank }}</td>
        <td>{{ row.time | format_record_time }}</td>
        <td>{{ row.date | format_record_date }}</td>
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root.records', page=pagination.prev_num) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root.records', page=pagination.next_num) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/search.html
{% extends "base.html" %}
{% block content %}
Search results
<table>
    <tr>
        <th>Type</th>
        <th>Name</th>
        <th>Steam Profile / Item url</th>
    </tr>
    {% for row in pagination.items %}
    <tr>
        <td>{{ row.type }}</td>
        {% if row.type == 'player' %}
        <td>{{ row.name | format_player_name(row.steam_id) }}</td>
        <td>{{ row.steam_id | format_profile_url }}</td>
        {% elif row.type == 'map' %}
        <td>{{ row.name | format_map_name }}</td>
        <td>{{ row.steam_id | format_workshop_url }}</td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% if pagination.has_prev %}<a href="{{ url_for('root.search', page=pagination.prev_num, search_string=search_string) }}">&lt;&lt; Previous</a>
{% else %}&lt;&lt; Previous
{% endif %} |
{% if pagination.has_next %}<a href="{{ url_for('root.search', page=pagination.next_num, search_string=search_string) }}">Next &gt;&gt;</a>
{% else %}Next &gt;&gt;
{% endif %}
{% endblock %}

qldf/root/templates/servers.j2
{% extends "base.j2" %}
{% block content %}
Server browser
<table>
    <tr>
        <th>Name</th>
        <th>Country</th>
        <th>Map</th>
        <th>World records</th>
        <th>Playercount</th>
        <th>Players</th>
        <th>Tags</th>
        <th>Last refresh</th>
    </tr>
    {% for server in servers %}
    <tr>
        <td>{{ server.name | format_server(server.address) }}</td>
        <td>{{ server.country }}</td>
        <td>{{ server.map | format_map_name }}</td>
        <td>{{ world_records | format_server_wrs(server.server_id) }}</td>
        <td>{{ players[server.server_id] | length }}/{{ server.max_players }}</td>
        <td>{{ players[server.server_id] | format_players }}</td>
        <td>{{ server.keywords }}</td>
        <td>{{ server.date_modified | format_record_date}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}